/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Estudiantes
 */
public class Interfaz extends javax.swing.JFrame {
    public ImageIcon imgs [];
    public String msgs[];
    public int ran;
    public int err;
    public String res[];

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        imgs = new ImageIcon[8];
        msgs = new String[30];
        
        // Desplazamiento de imagenes
        imgs[0]= new ImageIcon(getClass().getResource("/Vista/ini.jpg"));
        imgs[1]= new ImageIcon(getClass().getResource("/Vista/funo.jpg"));
        imgs[2]= new ImageIcon(getClass().getResource("/Vista/fdos.jpg"));
        imgs[3]= new ImageIcon(getClass().getResource("/Vista/ftres.jpg"));
        imgs[4]= new ImageIcon(getClass().getResource("/Vista/fcuatro.jpg"));
        imgs[5]= new ImageIcon(getClass().getResource("/Vista/fcinco.jpg"));
        imgs[6]= new ImageIcon(getClass().getResource("/Vista/fseis.jpg"));
        imgs[7]= new ImageIcon(getClass().getResource("/Vista/fin.jpg"));
        
        // Palabras a adivinar de tipo animal, paises, ciudades y frutas
        
        msgs[0]="Colombia".toUpperCase();
        msgs[1]="Cafe".toUpperCase();
        msgs[2]="Guacamaya".toUpperCase();
        msgs[3]="Amazonia".toUpperCase();
        msgs[4]="Francia".toUpperCase();
        msgs[5]="Banano".toUpperCase();
        msgs[6]="Bogota".toUpperCase();
        msgs[7]="Japon".toUpperCase();
        msgs[8]="Brasil".toUpperCase();
        msgs[9]="Manzana".toUpperCase();
        msgs[10]="Granadilla".toUpperCase();
        msgs[11]="Medellin".toUpperCase();
        msgs[12]="Uchuva".toUpperCase();
        msgs[13]="Cartagena".toUpperCase();
        msgs[14]="Argentina".toUpperCase();
        msgs[15]="Belgica".toUpperCase();
        msgs[16]="cali".toUpperCase();
        msgs[17]="Venezuela".toUpperCase();
        msgs[18]="Papaya".toUpperCase();
        msgs[19]="Mandarina".toUpperCase();
        msgs[20]="Tigre".toUpperCase();
        msgs[21]="Chimpance".toUpperCase();
        msgs[22]="Guayaba".toUpperCase();
        msgs[23]="Washington".toUpperCase();
        msgs[24]="California".toUpperCase();
        msgs[25]="Mora".toUpperCase();
        msgs[26]="Sandia".toUpperCase();
        msgs[27]="Inglaterra".toUpperCase();
        msgs[28]="China".toUpperCase();
        msgs[29]="Rusia".toUpperCase(); 
        iniciar();
        
    }
    public void iniciar() {
        //ERRORES EN 0
        err = 0;
        recima.setIcon(imgs[0]);
        texpnl.setText("");
        //Genera una palabra aleatoriamente
        ran = (int) 0 + (int) (Math.random() * ((msgs.length - 1) + 1));
        //SEPARA EL MENSAJE POR PALABRAS
        String pal[] = msgs[ran].split(" ");
        res = new String[msgs[ran].length() + 1];
        int j = 0;
        // seran los guiones que van debajo de las letras como una separacion_
        for (String pal1 : pal) {
            for (int i = 0; i < pal1.length(); i++) {
                texpnl.setText(texpnl.getText() + "_ ");
                res[j++] = "_";
            }
            texpnl.setText(texpnl.getText() + "\n");
            res[j++] = " ";
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        texpnl = new javax.swing.JTextPane();
        recima = new javax.swing.JButton();
        Reinciar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));

        texpnl.setBackground(new java.awt.Color(255, 255, 204));
        jScrollPane1.setViewportView(texpnl);

        recima.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/ini.jpg"))); // NOI18N

        Reinciar.setBackground(new java.awt.Color(255, 255, 204));
        Reinciar.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        Reinciar.setText("Reiniciar");
        Reinciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReinciarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ahorcado UD");

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 2, 18)); // NOI18N
        jLabel2.setText("Adivina ésta palabra");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/EUD.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(141, 141, 141))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(Reinciar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(224, 224, 224)))
                .addComponent(recima, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(172, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(Reinciar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(recima, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReinciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReinciarActionPerformed
        JOptionPane.showMessageDialog(null, "¿Seguro quieres reiniciar?");
        iniciar();
        
    }//GEN-LAST:event_ReinciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Reinciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton recima;
    private javax.swing.JTextPane texpnl;
    // End of variables declaration//GEN-END:variables
}
